# Generated by Django 4.1.7 on 2023-03-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user',
            new_name='created_by',
        ),
    ]
